---
- name: Converge
  hosts: all
  vars:
    consul_role: server
    consul_datacenter: "us-east-1"
    consul_encryptkey: "YKbtX0Gc3mnJ7QwaNwNYtg=="
    consul_cert: |
      -----BEGIN CERTIFICATE-----
      MIIDbzCCAlegAwIBAgIBCjANBgkqhkiG9w0BAQUFADBIMQswCQYDVQQGEwJVUzEO
      MAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjEYMBYGA1UECgwPQXVzdGlu
      Q2xvdWRHdXJ1MB4XDTIyMTEyMjE3MTIyMVoXDTMyMTExOTE3MTIyMVowVDEbMBkG
      A1UEAwwSKi5hdXN0aW5jbG91ZC5ndXJ1MQ4wDAYDVQQIDAVUZXhhczELMAkGA1UE
      BhMCVVMxGDAWBgNVBAoMD0F1c3RpbkNsb3VkR3VydTCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAKiHPmTx6012OVfbDnCN9jwwvf00I5NwLL37bkJTY1PL
      rljIMm8FZIiKsB9HMmWMJ2iHwhOL7ZAKQkhzlHmRhy6YKX/1Ky9pxYyCpVcXCPxR
      d1vGPMQpEVv1YLKAohC/wVod/qDHB2Cs9PwGkMuWpR1oMblkDe7LBiggTnyyezun
      PKTySYgg6/jujAFm7/CTtMB6bFyY72Cf4f6qMLdxji8WqrnPGOIsbKbkUaeWbz1R
      AEhc86oWDjBxJwAj1+n5J6aHVkuqQPLR4xxLBTHYtZhzodvXd4ob+Pvfdpjhe800
      pz+IEe0FtfEqXsa/FoNearUlLi3EwZT6MXOUug7dsjECAwEAAaNYMFYwCQYDVR0T
      BAIwADAdBgNVHQ4EFgQUIvHbsesTu0uEUG8y5AlSTSmzcocwCwYDVR0PBAQDAgWg
      MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQUFAAOC
      AQEAC3zUxRE+VeaH/NruV2lf7Hykz64KE3r54kfDsNbRAArRqYS4JjsSLSDT8Lvs
      RtRu1EeVDke4z4/Jm1UM5XyUI+N/dXoX377r5qvn+11x6/hkBT269MvN+xIfmGkN
      fnk2URSVjx25aisA/LEi4Z14asUxWotrVqvxwiePnt3VlsDMFSl0se4iTFAWjlKe
      Hs8QIbstq7XdIL3etDsvp1Paf6mR4H60sWIJDHdsPWBXNXET9h+uve2FW8l91YeM
      WffsXoNUy8xjqF+ev3xa9pSpkfmJFbB22Ba2dB3RIrSHpEaPFEkEWR+xmLG/UrHh
      iBU6aMD9YtWluP8gE6E02wBB3Q==
      -----END CERTIFICATE-----
    consul_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCohz5k8etNdjlX
      2w5wjfY8ML39NCOTcCy9+25CU2NTy65YyDJvBWSIirAfRzJljCdoh8ITi+2QCkJI
      c5R5kYcumCl/9SsvacWMgqVXFwj8UXdbxjzEKRFb9WCygKIQv8FaHf6gxwdgrPT8
      BpDLlqUdaDG5ZA3uywYoIE58sns7pzyk8kmIIOv47owBZu/wk7TAemxcmO9gn+H+
      qjC3cY4vFqq5zxjiLGym5FGnlm89UQBIXPOqFg4wcScAI9fp+Semh1ZLqkDy0eMc
      SwUx2LWYc6Hb13eKG/j733aY4XvNNKc/iBHtBbXxKl7GvxaDXmq1JS4txMGU+jFz
      lLoO3bIxAgMBAAECggEAeJMyr/Rp/qTsSBBhV2QqXUweUk+AeJdUW6TNcUTKFwTu
      O3UYqFf6YrqfYfGFfCP3ehFPaL6/fEPqwn13KDdXuZ2Ca5tUh3qsrWg3tYS0mBoN
      RKsjhNFBK0L3KR9hVIxtYPV+3Tco7yEvsjVcWVzxy4VltheA5G17fTAIF612/+jw
      RtyqV+PLTCmHctpW0/rEePZYnpaXF1aEkL6hUukhEaEUcGP7Is7k1SWdK7b+kQ6+
      aT1D288FqQDsHy/wAFmotqJ3LRTDGwHlJ1Lt+0KfTNF8JOw/6fBbnWISFndiOYh/
      TSizzFBAsJFIKcLG7U8LbxTxrMiTbl7nMWUu+9FacQKBgQDexmSkrpQ2WMdb0/CO
      gj2W2Sbwogj0MZSfXLCdOQkHngDd71E/T2jJRpYJURAK7l1C+F3ZB/TH8N/QboRq
      0NUVnYCKnzKK5MMQeAIGvtu2J2gD8dQ97Ul6a20l058e6vyn/0ciHyK4LzZqU+8d
      nbbIr+q8n66VUIyVb1V7RxGnPQKBgQDBqbK/OPwII2kmI/xMRHfYKbCVnniav9qT
      ntnT3b4/oVDoBXs8vpbOGSANtFaQNEIHccWhE/4jf0YY6WzlRSisMZ5TQckN4uu4
      tPr+tc/OB2PwTH4Yt4NkJWqPZr0AF0yrHQcTNdg4H3Hu+6vMR6l+/YL8678W6MNt
      a/7n8aIGBQKBgHtbnGtciJG3g10j9PbUw8n+IQPqlc6yjbvZFatZ49gl9BDw7iqC
      jGG4BmjOTHXhHB9zbHQ7ZZ45kZXXPNfxH61Cc+VO1iv3FNTPvz+A/CTXmU9l38MS
      3Dc/uUbS8i+qq5FTWE5as10ON7GVHLlnlcl3MCKWwZPI8K/m4IzNA8d5AoGAPBHP
      B9E9G6kgLFxtHZr/MWV9CGunLRjlS3SyTC0znbkDx3QrzaOwUy0n7BhL4V7UPErl
      6hixc4E+1OtSg6r3+rFJUrnNCymfxCMe13K9ikJwlVCkrDX/40hXzTMo3KZdeZX/
      Y84HyyC1zlLx7uMrh+BKiPj2xLxeIcqlvnwMraECgYEAlm2JzlhWeKJwfmkp9Ogu
      z1EJDpn3v2rtGMwLBYKpvcsrP01hBwbzPmwjBkqU340p63/c9Xvyj7F7dvc2GKOI
      eVldohWIH5fnF3iLwG1VXTMlPOBrCL/MTPaUGbQNMSV4x932zbRlOAgdBSylfMJ8
      2WQpoxX/Y4YsEQLYCttVqEE=
      -----END PRIVATE KEY-----
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      MIIDDDCCAfQCCQDl9o9ECe/+UTANBgkqhkiG9w0BAQsFADBIMQswCQYDVQQGEwJV
      UzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjEYMBYGA1UECgwPQXVz
      dGluQ2xvdWRHdXJ1MB4XDTIyMTEyMjE3MTIxMVoXDTMyMTExOTE3MTIxMVowSDEL
      MAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMQ8wDQYDVQQHDAZBdXN0aW4xGDAW
      BgNVBAoMD0F1c3RpbkNsb3VkR3VydTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
      AQoCggEBAN4dtGelwL35/RDCkDIzD13QxAHHvHWr1jCngk0edWYrjryJX3MAfMwR
      U9vAtTyzZBO2WKHZ+dGlGBICXBpwbJovIeAhRRf1gl81buxzZKzFAvq8bTzEbmLK
      AVjMzBHLhvkoSVurQuCiwryT6E8Eay+IA7au3dh01ydie3A0z9ax8PXwpfYJNBIF
      T+PhCJ4ilpm0v+PuHuad/XM/QsoYbZLVBdyWRjftMJwFhLz0NNRGCvJDi3QgEoww
      NUOch75O3BIQQ58XmQG+wGMaPk6lvTEs4t00UuQpRQF/dXipMjXO6KbSO0QmfcL1
      61cfzx/lPQt2fL6FptUqY675cqG0RTsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
      YIQOk7RXx2HRGzN8FYnPczofuOsmCTCmQ9lPYOKr3GUCZ87La546Tpugv/51Cr1w
      TYTphqMTpnozQrTNpPrj451mKWupxZPY/sAfrAzOA+dLNT6Jw9Vcrtt9m1xMZLrR
      +LFQBw/Unkj0IVauhaqmPHnXldCD6lyq0FNF/f8OtJaZugFa5/hi8yn/Ua6xunmt
      tnf9IJRYHgcVb4M8FahEngKBo4cvgakuAByb3SK2i9jzcHmWP6YhlqQSn88PIWEM
      +UHY0BNaBQhyyEb/T69G+40Yue1+M93FdUqkR4oaMKwgkUBUx+mny7OUb9uI2qJQ
      tTJ7ZpZ+v8Qx1YxvzvF9lQ==
      -----END CERTIFICATE-----

  roles:
    - austincloudguru.consul
