---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu-18.04
    image: austincloud/molecule-ubuntu-18.04
    privileged: True
    command: /sbin/init
  - name: amazonlinux
    image: austincloud/molecule-amazonlinux-1
    privileged: True
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
